language: node_js
node_js:
  - '6.4.0'
notifications:
  email: false
before_install:
  - travis_retry nvm install 6.4.0
  - if [ $TRAVIS_SECURE_ENV_VARS == "true" ]; then
      npm install request;
      npm run update-package;
    fi
env:
  global:
    - secure: "diFXzAzyms6IK/FPYYw/dM6MjvgfCJdlko+k0wLcwr72dPHq4iN/c/YuhHBOxCiQCtYhPqzB5Y+Kz5uB4y8sXzI6ypYOvDxOPugQrGomp6EDJtADf9Vpj1EjlP84slKdKrePCNcttyJk+zAJolRhWIZz1SFqb1zRgbXPcKMOnGk="
    - secure: "IefyZiRK6R6a1RuMVRj1y9APRqivqR8uZ8sbsgYfPe3R2kKqN/Riu+hMG/c4P1ZIrvpd/6EYimdwsn+E4ex6YLe+Bhx3/igw9x/WEqZ56N61zWgTt8G7B6HtVs2yfBgiyhXY9sNJwgy0xePQDfH4REfkmeVL+bslg9pNtIITqrU="
    - secure: "ERN4GUhV/WtPHOhB1HzAIw+G0xow9vAWwx8HpdD2kUjGl7QoNtVk6Duys7txq0EiBIY4vDZBfvU+yVpUyswJvEaw/5q+dZ+4Py311uebjbqHSdQNiY9hHCqJ2TGng0uVWz+2tzV5CJQ7e+jXaHwcUBv38ha74hO9y6nuh2hixeI="
script:
  - if [ $TRAVIS_SECURE_ENV_VARS == "true" ]; then
      npm run get-test-utils && npm run test ; npm run lint ; npm run report;
    else
      npm run merge;
    fi
